app = "lazycoder"
primary_region = "ord"

[build]
  image = "cardellier/opencode:latest"

[mounts]
  source = "data"
  destination = "/data"
  initial_size = "16gb"

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

[vm]
  size = "shared-cpu-2x"
  memory = 2048
